#define BLUEPRINT_CAT_MISC "misc"
#define BLUEPRINT_CAT_FOOD_PROCESSING "food processing"
#define BLUEPRINT_CAT_UTILS "utils"
#define BLUEPRINT_CAT_DECORATION "decoration"
#define BLUEPRINT_CAT_CONSTRUCTION "construction"
#define BLUEPRINT_CAT_CRAFTSMANSHIP "craftsmanship"
