#define PART_NONE "part_none"
#define PART_ANY "any_part"
#define PART_HANDLE "handle"
#define PART_HEAD "head"
#define PART_PLANKS "planks"
#define PART_INGOT "ingot"
#define PART_STONE "stone"
#define PART_LEATHER "leather"
#define PART_CLOTH "cloth"
#define PART_STRING "string"

#define MATERIAL_STONE "stone"
#define MATERIAL_WOOD "wood"
#define MATERIAL_METAL "metal"

#define MATERIAL_ICON_KEY "[type]-[islist(materials) ? list2params(materials) : materials]-[_file]-[state]"
